name: Validate Terraform
on:
  push:
    branches:
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.6.0

      - name: Configure AWS IdP Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::850744974572:role/AWSA-SK-GitHubTerraformBackend-Role
          role-session-name: GitHubActions
          retry-max-attempts: 5
          aws-region: eu-west-2

      - name: Terraform Init
        run: |
          terraform init -reconfigure \
          -backend-config="bucket=${{ secrets.TF_BUCKET }}" \
          -backend-config="region=eu-west-2" \
          -backend-config="assume_role={role_arn=\"arn:aws:iam::850744974572:role/AWSA-SK-GitHubTerraformBackend-Role\"}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -var 'hello=world'